services:
  db:
    image: postgres:15
    container_name: fintech-db
    restart: always
    environment:
      POSTGRES_USER: fintech_user
      POSTGRES_PASSWORD: fintech_pass
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
